### ISSUE TITLE
length of 'dimnames' [1] not equal to array extent

### ISSUE THREAD

**Issue by PerOG7** [nlmixr2/lotri#17]
Hi,

Using

```r
lotri(eta.A+eta.B ~  c(
  5.08E+00,
  -4.42E-01,  2.31E-01))
```

works as expected. However, 

```r
omega<-c(
  5.08E+00,
  -4.42E-01,  2.31E-01)

lotri(eta.A+eta.B ~ omega)
```
gives the Error message

> Error in dimnames(.ret) <- list(env$names, env$names) :   length of 'dimnames' [1] not equal to array extent`

**Comment by mattfidler** [comment]
Thanks for reporting @PerOG7 

This is because of the non standard evaluation of `lotri`;  I will look into it soon.

**Comment by mattfidler** [comment]
This is now fixed in the development branch

``` r
library(lotri)

omega<-c(
  5.08E+00,
  -4.42E-01,  2.31E-01)

lotri(eta.A+eta.B ~ omega)
#>        eta.A  eta.B
#> eta.A  5.080 -0.442
#> eta.B -0.442  0.231
```

<sup>Created on 2023-09-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by PerOG7** [comment]
Thanks!
Per

Per Olsson Gisleskog
Managing Director and Principal Consultant
POG Pharmacometrics Ltd
London, UK
+44 7949 075548
***@***.***
www.pog-p.com <http://www.pog-p.com/>




On 30 Sep 2023, at 01:24, Matthew Fidler ***@***.***> wrote:


This is now fixed in the development branch

library(lotri)

omega<-c(
  5.08E+00,
  -4.42E-01,  2.31E-01)

lotri(eta.A+eta.B ~ omega)
#>        eta.A  eta.B
#> eta.A  5.080 -0.442
#> eta.B -0.442  0.231
Created on 2023-09-29 with reprex v2.0.2 <https://reprex.tidyverse.org/>
