### ISSUE TITLE
Make syntax errors into errors only (and not include a message)

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/lotri#2]
Related to #1.

Previously (before merging #1), syntax errors would yield multiple messages and then an error.  Now (after merging #1), syntax errors yield one message and then one error:

https://github.com/nlmixr2/lotri/blob/5b7012c0406e71b550ac46f5eb62df2a65ba6cfc/R/err.R#L27-L28

As discussed in #1, does it make sense to switch the text from the message to just be the text of an error.  Specifically, the above two lines of code would become one:

```
stop(paste(messageText, collapse="\n"), call. = FALSE)
```

**Comment by mattfidler** [comment]
I understand now.  

I have tried this approach.  At the time I tried it removed the bold and formatting which can be useful to identify errors.  

I have not tried with the current R and Rsudio and emacs.  It could be Ok.

This error was made to match the parsing errors in rxode2. In rxode2 this cannot be done easily since the messaging is in C.

So, how important is consistency? I think this is similar to how devtools reports errors...

**Comment by billdenney** [comment]
Overall, it's not important.  The idea was to put all of the error message into the error itself.  And, the question was just based on that idea.

It was (kinda) important to put it all into a single message so that testing could be made silent easily.

If you had an issue, then we can just close this.

**Comment by mattfidler** [comment]
It thought simply the suppressing of the messages would remove this.  Did `testthat` stop suppressing messages in 3?

Anyhow, since it is difficult in `rxode2`, I suggest tabling this for now.  This is not a "no" but maybe lets think about why.

**Comment by billdenney** [comment]
Testthat edition 3 changes the way that `expect_warning()` and `expect_message()` works so that they only capture one message/warning.  As I understand it, the rationale for this was to allow for checking for multiple messages/warnings.  So, collapsing multiple messages/warnings when they are related works more in line with the way that current testthat handles it.

Since this is so minor, I'll close the issue for now.
