### ISSUE TITLE
CRAN fixes

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/lotri#30]
That is

        lotri rego rlibkriging

See the logs (and README.txt) at https://www.stats.ox.ac.uk/pub/bdr/gcc15/ .

RcppArmadillo has been updated today to install under g++ 15, so
packages using it install whereas yours do not.  We would prefer that
you used RcppArmadillo so we don't have to do the same work 3 more
times, but if you are unwilling to do that you need to copy the changes
from RcppArmadillo (or in the case of lotri, get the cpp11armadilo
maintainer to do so).

Please correct before 2025-01-10 to safely retain your package on CRAN.

**Comment by pachadotdev** [comment]
This was fixed here https://cran.r-project.org/package=cpp11armadillo

**Comment by mattfidler** [comment]
Thanks
