### ISSUE TITLE
Possible Valgrind Issues

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/lotri#6]
Two of these appear to be related to brio (so, outside of our code base), and the other two are less clear to me.  Do either of these require modification?

https://github.com/billdenney/nlmixr2CRANtesting/blob/b887c1a8660e594a31423a33e7dd475811cc7509/outputs/lotri_test_valgrind.txt#L285-L361

**Comment by mattfidler** [comment]
I don't think they do...
